#! /bin/bash
set -e

source "./package.info"

mkdir -p pkg/libs

# Don't bother copying these if we are on a platform they don't exist
if [[ -d "/lib/aarch64-linux-gnu" ]]; then 
  cp /lib/aarch64-linux-gnu/libpcre.so.3 pkg/libs
  cp /usr/lib/aarch64-linux-gnu/libunistring.so.2 pkg/libs
  cp /usr/lib/aarch64-linux-gnu/libpsl.so.5  pkg/libs
  cp /usr/lib/aarch64-linux-gnu/libpcre2-8.so.0 pkg/libs
  cp oga-controls/source/oga_controls pkg
fi

echo "$PKG_VERSION" > pkg/version