#This Dockerfile will be used to encapsulate the 'build' when './build --docker-image' is set
ARG DOCKER_IMAGE=""
FROM ${DOCKER_IMAGE} as prod

ARG PACKAGE=""

RUN mkdir -p ./$PACKAGE/

#NOTE: important that Dockerfile.build is copied as it *always* exists
#      The other files are technically optional
COPY Dockerfile.build build* package* conf* ./$PACKAGE/
COPY clone-source ./
RUN bash -c "source ./clone-source && clone_source $PACKAGE"

WORKDIR ./$PACKAGE/

RUN [ -x ./build ] && cd source && ../build || echo "no build"