#This Dockerfile will be used to encapsulate the 'build' when './build --docker-image' is set
ARG DOCKER_IMAGE=""
FROM ${DOCKER_IMAGE}
ARG PACKAGE=""

COPY ./ ./$PACKAGE
RUN ./build $PACKAGE --no-docker