#!/bin/bash
set -e

# Current directory of the script
DIR="$(realpath $( dirname "${BASH_SOURCE[0]}" ))"
source "${DIR}/control.txt"

ESUDO="$(get_sudo)"
DEVICE="$(get_device)"

if [[ ! -f "${DIR}/conf/cdogs-sdl/options.cnf" ]]; then
  config_type=480 #oga, rk2020
  if [[ "${DEVICE}" == "ogs" ]]; then
    config_type=ogs
  elif [[ "${DEVICE}" == "chi" || "${DEVICE}" == "rg351v" || "${DEVICE}" == "rg351mp"  ]]; then
    config_type=640
  fi
  mv -f "${DIR}/conf/cdogs-sdl/options.cnf.${config_type}" "${DIR}/conf/cdogs-sdl/options.cnf"
  rm -f ${DIR}/conf/cdogs-sdl/options.cnf.*
fi

$ESUDO  rm -rf ~/.config/cdogs-sdl
ln -sfv "${DIR}/conf/cdogs-sdl/" ~/.config/

cd "${DIR}/data"
export SDL_GAMECONTROLLERCONFIG="$(get_controls)"
./cdogs-sdl