#! /bin/bash
set -e

# assumptions
# - that git/download is checked out in 'source'
# - the current directory is source
mkdir -p bld && cd bld
cmake ..
#TODO: readd
#make smw -j4 # -jN = build on N threads
