#! /bin/bash
# Common functions used across ports
#  - Will be copied into the package next to run.sh
#
# The suggested way to source this file from run.sh is:
# -----------------------------------------------------
# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# source "${DIR}/global-functions"
# -----------------------------------------------------
# Utilizing DIR instead of ./ means the script can be called from any directory
#
# All files in this script should suppport the $ROOT_DIR variable which will default to ''.  This allows
# creating mock environments for testing
#
# Functions are designed to be called in the format:
# DEVICE=$(get_device)
# DEV NOTE: If debug output is needed in a function, output information with `echo_err` (stderr) as
# anything output to stdout will be included in the returned device, etc


ROOT_DIR=

# Gets the current device:
#  Supported devices: rg351p, rg351p (rg351m), rg351mp, oga, rk2020, ogs (same as rgb10max), chi, unknown
function get_device() {
  local param_device="unknown"
  if [[ -e "${ROOT_DIR}/dev/input/by-path/platform-ff300000.usb-usb-0:1.2:1.0-event-joystick" ]]; then
    #anbernic rg351v and rg351p
    if [[ -e "${ROOT_DIR}/dev/input/by-path/platform-rg351-keys-event" ]]; then #volume buttons
      param_device="rg351v"
    else
      param_device="rg351p"
    fi
  elif [[ -e "${ROOT_DIR}/dev/input/by-path/platform-odroidgo2-joypad-event-joystick" ]]; then
    if [[ -f "${ROOT_DIR}/etc/emulationstation/es_input.cfg" ]] \
       && grep -q "190000004b4800000010000001010000" "${ROOT_DIR}/etc/emulationstation/es_input.cfg" &> /dev/null; then
      param_device="oga"
  	else
  	  param_device="rk2020"
  	fi
  elif [[ -e "${ROOT_DIR}/dev/input/by-path/platform-odroidgo3-joypad-event-joystick" ]]; then
    if [[ -e "${ROOT_DIR}/dev/input/by-path/platform-rg351-keys-event" ]]; then
      param_device="rg351mp"
    else
      param_device="ogs"
    fi
  fi
  echo "${param_device}"
}

# This is the 'param_device' to pass to oga_controls.
# Must be one of: anbernic, chi, oga, ogs, rk2020
function get_oga_device() {
  local device
  device="$(get_device)"
  if [[ "${device}" == "rg351v" || "${device}" == "rg351v" ]]; then
    device="anbernic"
  elif [[ "${device}" == "rg351mp" ]]; then
    device="ogs"  #TODO: validate this works as 351mp uses same controller - I think this is true
  elif [[ "${device}" == "unknown" ]]; then
    device="chi"  #FIXME - ideally we don't want to default to chi and should identify chi in 'get_device'
  fi
  echo "${device}"
}

function get_sdl_controller_config() {
  local oga_device
  local sdl_controllerconfig
  oga_device="$(get_oga_device)"
  if [[ "${oga_device}" == "anbernic" ]]; then
    sdl_controllerconfig="03000000091200000031000011010000,OpenSimHardware OSH PB Controller,a:b0,b:b1,x:b3,y:b2,leftshoulder:b4,rightshoulder:b5,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftx:a0~,lefty:a1~,leftstick:b8,lefttrigger:b10,rightstick:b9,back:b7,start:b6,rightx:a2,righty:a3,righttrigger:b11,platform:Linux,"
  elif [[ "${oga_device}" == "oga" ]]; then
    sdl_controllerconfig="190000004b4800000010000001010000,GO-Advance Gamepad (rev 1.1),a:b1,b:b0,x:b2,y:b3,leftshoulder:b4,rightshoulder:b5,dpdown:b9,dpleft:b10,dpright:b11,dpup:b8,leftx:a0,lefty:a1,back:b12,leftstick:b13,lefttrigger:b14,rightstick:b16,righttrigger:b15,start:b17,platform:Linux,"
  elif [[ "${oga_device}" == "rk2020" ]]; then
    sdl_controllerconfig="190000004b4800000010000000010000,GO-Advance Gamepad,a:b1,b:b0,x:b2,y:b3,leftshoulder:b4,rightshoulder:b5,dpdown:b7,dpleft:b8,dpright:b9,dpup:b6,leftx:a0,lefty:a1,back:b10,lefttrigger:b12,righttrigger:b13,start:b15,platform:Linux,"
  elif [[ "${oga_device}" == "ogs" ]]; then
    sdl_controllerconfig="190000004b4800000011000000010000,GO-Super Gamepad,platform:Linux,x:b2,a:b1,b:b0,y:b3,back:b12,guide:b14,start:b13,dpleft:b10,dpdown:b9,dpright:b11,dpup:b8,leftshoulder:b4,lefttrigger:b6,rightshoulder:b5,righttrigger:b7,leftstick:b15,rightstick:b16,leftx:a0,lefty:a1,rightx:a2,righty:a3,platform:Linux,"
  elif [[ "${oga_device}" == "chi" ]]; then
    sdl_controllerconfig="19000000030000000300000002030000,gameforce_gamepad,leftstick:b14,rightx:a3,leftshoulder:b4,start:b9,lefty:a0,dpup:b10,righty:a2,a:b1,b:b0,guide:b16,dpdown:b11,rightshoulder:b5,righttrigger:b7,rightstick:b15,dpright:b13,x:b2,back:b8,leftx:a1,y:b3,dpleft:b12,lefttrigger:b6,platform:Linux,"
  fi
  echo "${sdl_controllerconfig}"

}

# Gets the current OS
#  Options: ArkOS, 351ELEC, TheRA, ubuntu, unknown
#  NOTE: ubuntu is to be used as fallback for testing off-device (mostly applicable for portmaster)
function get_os() {
  local param_os="unknown"

  if [[ -f "${ROOT_DIR}/boot/rk3326-rg351v-linux.dtb" || -d "${ROOT_DIR}/opt/system/Advanced/" ]]; then
    param_os="ArkOS"
  elif [[ -e "${ROOT_DIR}/storage/.config/.OS_ARCH" ]]; then
    param_os="351ELEC"
  elif [[ -e "${ROOT_DIR}/usr/share/plymouth/themes/text.plymouth" \
          && $(grep "title=" "${ROOT_DIR}/usr/share/plymouth/themes/text.plymouth") == *"TheRA"* ]]; then
    param_os="TheRA"
  elif grep -q "ID=ubuntu" ${ROOT_DIR}/etc/os-release &> /dev/null; then
    param_os="ubuntu"
  fi
  echo "${param_os}"
}

# Whether to use sudo
function get_sudo() {
  local os
  os="$(get_os)"
  if [[ "${os}" == "351ELEC" ]]; then
    echo ""
  else
    echo "sudo"
  fi
}

function get_tools_dir() {
  os=$(get_os)
  local toolsfolderloc="${ROOT_DIR}/opt/tools"
  if [[ "351ELEC" == "${os}" ]]; then
    toolsfolderloc="${ROOT_DIR}/storage/roms/tools"
  elif [[ "TheRA" == "${os}" ]]; then
    toolsfolderloc="${ROOT_DIR}/opt/system/Tools"
  elif [[ "ArkOS" == "${os}" ]]; then
    toolsfolderloc="${ROOT_DIR}/opt/tools"
  fi
  echo "${toolsfolderloc}"
}

function get_roms_dir() {
  local os
  os=$(get_os)
  local romsfolderloc="${ROOT_DIR}/opt/roms"
  if [[ "351ELEC" == "${os}" ]]; then
    romsfolderloc="${ROOT_DIR}/storage/roms/"
  elif [[ "TheRA" == "${os}" ]]; then
    romsfolderloc="${ROOT_DIR}/opt/system/Roms"
  elif [[ "ArkOS" == "${os}" ]]; then
    romsfolderloc="${ROOT_DIR}/opt/roms"
  fi
  echo "${romsfolderloc}"
}
function get_ports_dir() {
  echo "$(get_roms_dir)/ports"
}

function get_console() {
  local os
  os=$(get_os)
  local console="/dev/tty0"
  if [[ "ubuntu" == "${os}" || "unknown" == "${os}" ]]; then
    console="/dev/stderr"
  fi
  echo "${console}"
}

function get_hotkey() {
  local hotkey="Select"
  local device
  device="$(get_device)"

  if [[ "${device}" == "oga" ]]; then
	  hotkey="Minus"
  elif [[ "${device}" == "chi" ]]; then
    hotkey="1"
  fi
  echo "${hotkey}"
}

function in_china() {
  ISITCHINA=$(curl -s --connect-timeout 30 -m 60 http://demo.ip-api.com/json | grep -Po '"country":.*?[^\\]"')
  local in_china=false
  if [[ "$ISITCHINA" == "\"country\":\"China\"" ]]; then
    in_china=true
  fi
  echo "${in_china}"
}

# outputs to stderr
function echo_err() {
  echo "$@" 1>&2;
}

#The below code only runs when this file is executed (not sourced)
#  Ex:  Please run `bash ./global-functions` and give us the output
# It's meant to help debugging on devices and should have output to help debug
# each function in this file.
#
# Output format currently allows being sourced by bash as variables as this might
# be useful in the future
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "OS=$(get_os)"
  echo "DEVICE=$(get_device)"
  echo "TOOLSDIR=$(get_tools_dir)"
  echo "ROMSDIR=$(get_roms_dir)"
  echo "CONSOLE=$(get_console)"
  echo "HOTKEY=$(get_hotkey)"
  echo "IN_CHINA=$(in_china)"
fi