#! /bin/bash
set -e

# assumptions
# - that git/download is checked out in 'source'
# - the current directory is source
mkdir -p bld
pushd bld
cmake -DCMAKE_INSTALL_PREFIX=../pkg ..
make -j$(nproc)
make install