#! /bin/bash
set -e
DIR="$(realpath $( dirname "${BASH_SOURCE[0]}" ))"

for directory in ${DIR}/*/; do
  directory=${directory%/}
  echo "directory: $directory"
  if [ -f "${directory}/package.info" ]; then
    PKG_LIBRARY=""
    source "${directory}/package.info"
    TO_BUILD="$(basename ${directory})"
    if [[ "${PKG_LIBRARY}" == "true" ]]; then
      echo "Not building libraries explicitly"
    else
      echo "build-all: building: ${TO_BUILD}"
      ${DIR}/build "${TO_BUILD}" "$@"
    fi
  else
    echo "No package.info found for: ${directory}"
  fi
done
