#! /bin/bash
set -e
DIR="$(realpath $( dirname "${BASH_SOURCE[0]}" ))"

for directory in ${DIR}/*/; do
  directory=${directory%/}
  echo "directory: $directory"
  if [ -f "${directory}/package.info" ]; then
    source "${directory}/package.info"
    TO_BUILD="$(basename ${directory})"
    echo "build-all: building: ${TO_BUILD}"
    ${DIR}/build "${TO_BUILD}" "$@"
  else
    echo "No package.info found for: ${directory}"
  fi
done
