#This Dockerfile will be used to encapsulate the 'build' when './build --docker-image' is set
ARG DOCKER_IMAGE=""
FROM ${DOCKER_IMAGE} as prod

ARG PACKAGE=""

RUN mkdir -p ./$PACKAGE/pkg
WORKDIR ./$PACKAGE/

COPY clone-source package.info* ./
RUN bash -c "source ./clone-source && ls -lah && clone_source $PACKAGE ./"

#NOTE: important that Dockerfile.build is copied as it *always* exists
#      The other files are technically optional
COPY Dockerfile.build build* ./

RUN [ -x ./build ] && cd source && ../build || echo "no build"