ARG BASE_IMAGE=debian:buster-20211011
FROM $BASE_IMAGE as base

COPY ./_global/global* /_global/
COPY ./_global/oga_controls /_global/
COPY ./build* /
WORKDIR /

# Test global functions
FROM base as test
RUN apt-get update && apt-get install -y bats curl dialog wget && rm -rf /var/lib/apt/lists/*
COPY ./_global/test /_global/test
RUN cd /_global/test && bats global-functions.bats

FROM base

